name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - master  # master 브랜치에 푸시될 때만 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/fastapi-mlops
          git pull origin master
          if [ ! -d ".venv" ]; then
            python3 -m venv .venv
          fi
          source .venv/bin/activate
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
          nohup uvicorn inference:app --reload --host 0.0.0.0 --port 8000 & diswon
