name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - master  # main 브랜치에 푸시될 때만 트리거1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}       # EC2 인스턴스의 IP 주소
        username: ${{ secrets.EC2_USER }}   # EC2 사용자 이름 (예: ubuntu)
        key: ${{ secrets.EC2_SSH_KEY }}     # SSH 개인 키
        script: |
          cd /home/ec2-user/fastapi-mlops
          git pull origin master
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
          uvicorn inference:app --reload --host 0.0.0.0 &
