name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Zip the function
      run: |
        zip -r9 function.zip . -x ".venv/*" ".git/*" "tests/*" "*.pyc" .

    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@v0.2.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: 'ap-northeast-2'  # 사용 중인 AWS 리전
        function_name: 'mlops'  # Lambda 함수 이름
        zip_file: 'function.zip'
